/**
 * layout.tsx — Root layout for Oystr
 *
 * This is the top-level layout that wraps every page.
 * It loads:
 *   - Google Fonts (Share Tech Mono + IBM Plex Mono)
 *   - PWA meta tags for mobile install
 *   - The BottomNav navigation bar
 *   - The OfflineBanner for connectivity status
 *
 * Every page in the app inherits this layout automatically.
 */

import type { Metadata, Viewport } from "next";
import { Share_Tech_Mono, IBM_Plex_Mono, VT323 } from "next/font/google";
import "./globals.css";
import BottomNav from "@/components/shared/BottomNav";
import OfflineBanner from "@/components/shared/OfflineBanner";
import InstallPrompt from "@/components/shared/InstallPrompt";
import ServiceWorkerRegistration from "@/components/shared/ServiceWorkerRegistration";
import SplashScreen from "@/components/shared/SplashScreen";
import OnboardingOverlay from "@/components/shared/OnboardingOverlay";

/* ========================================
 * FONT LOADING
 * next/font/google automatically self-hosts these fonts,
 * so no requests are sent to Google from the user's browser.
 * The 'variable' option creates a CSS custom property we
 * can reference in our Tailwind theme.
 * ======================================== */

/** Share Tech Mono — primary dot-matrix display font */
const shareTechMono = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-share-tech-mono",
  display: "swap",
});

/** IBM Plex Mono — secondary font for readable body text */
const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
  display: "swap",
});

/** VT323 — retro terminal font for departure boards */
const vt323 = VT323({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-vt323",
  display: "swap",
});

/* ========================================
 * METADATA
 * Used by Next.js to generate <head> tags.
 * Includes PWA-related tags for mobile install.
 * ======================================== */
export const metadata: Metadata = {
  /*
   * Base URL for resolving OG images and other metadata URLs.
   * oystrapp.vercel.app is the actual production domain for this
   * project on Vercel — oystr.vercel.app is owned by someone else
   * entirely and happens to be squatted. Anything pointing at
   * oystr.vercel.app would hit the wrong site.
   */
  metadataBase: new URL("https://oystrapp.vercel.app"),
  title: "Oystr - London Transport",
  description:
    "Live London transport departures, journey planning, and offline timetables",
  /* PWA manifest link */
  manifest: "/manifest.json",
  /* Apple-specific PWA settings */
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Oystr",
  },
  /* Apple touch icon for iOS home screen */
  icons: {
    apple: "/icons/icon-192.png",
  },
  /* Open Graph for social sharing (image auto-generated by opengraph-image.tsx) */
  openGraph: {
    title: "Oystr - London Transport",
    description: "Live departures and journey planning for London transport",
    type: "website",
    url: "https://oystrapp.vercel.app",
    siteName: "Oystr",
  },
  /* Twitter/X card — shows a large image preview when shared */
  twitter: {
    card: "summary_large_image",
    title: "Oystr - London Transport",
    description: "Live departures and journey planning for London transport",
  },
};

/** Viewport configuration — separate from metadata in Next.js 15 */
export const viewport: Viewport = {
  /* Dark theme colour for the browser chrome */
  themeColor: "#0a0a0a",
  /* Standard mobile viewport settings */
  width: "device-width",
  initialScale: 1,
  maximumScale: 5, /* Allow pinch-to-zoom for accessibility */
  /* Ensure content respects the safe area on notched phones */
  viewportFit: "cover",
};

/* ========================================
 * ROOT LAYOUT COMPONENT
 * ======================================== */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${shareTechMono.variable} ${ibmPlexMono.variable} ${vt323.variable} h-full`}
    >
      <head>
        {/*
         * iOS PWA splash screens.
         * These show the app icon centered on the dark background while the
         * app loads from the home screen. One tag per device screen size.
         * Generated via the icon + background color in the manifest.
         *
         * Common iOS screen sizes (portrait, 3x scale):
         *   iPhone 15 Pro Max: 1290x2796
         *   iPhone 15 / 14:   1170x2532
         *   iPhone SE 3:      750x1334
         *   iPad Pro 12.9":   2048x2732
         */}
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512.png"
          media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512.png"
          media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512.png"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512.png"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
        />
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512.png"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
        />
      </head>
      <body className="min-h-dvh flex flex-col bg-board-bg text-amber antialiased pt-[env(safe-area-inset-top)]">
        {/* Splash screen — shows once on first visit */}
        <SplashScreen />

        {/* Register service worker for offline caching */}
        <ServiceWorkerRegistration />

        {/* Offline banner — only shows when there's no internet */}
        <OfflineBanner />

        {/* Install prompt — shows for first-time visitors when app is installable */}
        <InstallPrompt />

        {/* Onboarding — 4-step walkthrough for first-time users */}
        <OnboardingOverlay />

        {/*
         * Main content area.
         *
         * flex-1 lets main fill the space between banners and nav. The
         * bottom padding clears the fixed BottomNav (3.5rem = h-14) plus
         * the safe-area inset plus a small visual buffer so content
         * doesn't tuck right up against the nav.
         */}
        <main
          className="flex-1 page-transition min-h-0"
          style={{
            paddingBottom:
              "calc(3.5rem + env(safe-area-inset-bottom, 0px) + 0.5rem)",
          }}
        >
          {children}
        </main>

        {/* Bottom tab navigation — always visible, fixed to viewport bottom */}
        <BottomNav />
      </body>
    </html>
  );
}
